server:
  port: 8080

spring:
  application:
    name: careo-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/careo
    username: careo
    password: careo
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

